// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Construir DATABASE_URL desde variables de entorno individuales si no existe
function getDatabaseUrl(): string {
  // Si DATABASE_URL ya existe, usarla (útil para Vercel Postgres o servicios similares)
  if (env("DATABASE_URL")) {
    return env("DATABASE_URL");
  }
  
  // Si no, construir desde variables individuales (compatible con PostgreSQL tradicional)
  const host = env("DB_HOST") || "localhost";
  const port = env("DB_PORT") || "5432";
  const user = env("DB_USER") || "postgres";
  const password = env("DB_PASSWORD") || "";
  const database = env("DB_NAME") || "";
  const ssl = env("DB_SSL") === "true" ? "?sslmode=require" : "";
  
  return `postgres://${user}:${password}@${host}:${port}/${database}${ssl}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
